import type { NextPage } from 'next';
import Head from 'next/head';
import { Suspense } from 'react';
import dynamic from 'next/dynamic';
import styles from '../styles/Home.module.css';

const DynamicFooter = dynamic(() => import('../components/Footer'), {
  suspense: true,
})

const Home: NextPage = () => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Cat App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Cat.js!</a>
        </h1>

        <p><img src="/images/cat-1.jpeg" alt="cat 1" /></p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>


          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Dummy &rarr;</h2>
            <p>Lorem Ipsum example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Random &rarr;</h2>
            <p>
              Ramdom code snippets for everyday developer.
            </p>
          </a>
        </div>
      </main>

      <Suspense fallback={`Loading...`}>
        <DynamicFooter />
      </Suspense>

    </div>
  )
}

export default Home
